settings:
  variables:
    entity_tablet: switch.galaxy_tab_a_screensaver
    entity_browser_mod: media_player.tablet
    translate_unknown: Ok채nt
    translate_idle: Inaktiv
    translate_home: Ja
    translate_not_home: Nej
    translate_available: tillg채nglig
    translate_no_updates: Inga uppdateringar
    translate_update_available: uppdatering tillg채nglig
    translate_updates_available: uppdateringar tillg채ngliga
