update_entities:
  action: >
    [[[
      hass.callService('homeassistant', 'update_entity', {
          entity_id: [
            'sensor.udm_unifios'
          ]
      });
    ]]]
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: UniFi Dream Machine
    card_mod:
      style:
        #popup header
        .:
    content:
      type: vertical-stack
      cards:
        - type: entities
          state_color: true
          card_mod:
            class: content
          entities:

            - entity: sensor.ikuai_online_user
              secondary_info: last-changed

            - entity: sensor.ikuai_wan_ip
              name: 公网ip

            - type: custom:bar-card
              width: 55%
              height: 2em
              decimal: 0
              unit_of_measurement: '%'
              positions:
                icon: outside
                indicator: 'off'
                name: outside
              severity:
                - color: '#6d2525'
                  from: 90
                  to: 999
              entity_row: true
              entities:
                - entity: sensor.ikuai_cpu
                - entity: sensor.ikuai_memory
                - entity: sensor.ikuai_totaldown
                
            - entity: sensor.ikuai_upload

        - type: custom:mod-card
          card_mod:
            style:
              hui-horizontal-stack-card$: |
                #root {
                  justify-content: space-evenly !important;
                  padding: var(--tablet-popup-button-padding);
                }
          card:
            type: horizontal-stack
            cards:
              - type: custom:button-card
                name: Nätverksenheter
                icon: mdi:devices
                tap_action:
                  action: url
                  url_path: http://192.168.50.252
                template: icon_name

              - type: custom:button-card
                name: System
                icon: mdi:cog
                tap_action:
                  action: url
                  url_path: http://192.168.50.252
                template: icon_name
