action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Matte
    card_mod:
      style:
        #popup header
        .:
    style: >
      --popup-max-width: 400px;
    content:
      type: vertical-stack
      cards:
        - type: entities
          card_mod:
            class: content
          entities:
            - entity: device_tracker.hostname2
              secondary_info: last-changed

        - type: history-graph
          card_mod:
            style: |
              ha-card > div {
                padding: 0 2em 1em 1.6em !important;
              }
          entities:
            - entity: device_tracker.hostname2

        - type: glance
          card_mod:
            style: |
              ha-card > div {
                padding: 1em 1.5em 0.2em 1em !important;
                box-sizing: content-box;
              }
          show_state: false
          entities:

            - entity: device_tracker.hostname2
              name: Router
              icon: mdi:wifi
              card_mod:
                style: &state |
                  state-badge {
                    color: {{ is_state(config.entity, 'home') | iif('#3182b7', '#3c3f3f') }};
                  }

            - entity: device_tracker.hostname2
              name: Bluetooth
              icon: mdi:bluetooth
              card_mod:
                style: *state

            - entity: device_tracker.hostname2
              name: Position
              icon: cil:iphone-modern
              card_mod:
                style: *state

        - type: custom:mod-card
          card_mod:
            style:
              hui-horizontal-stack-card$: |
                #root {
                  justify-content: space-evenly !important;
                  padding: var(--tablet-popup-button-padding);
                }
          card:
            type: horizontal-stack
            cards:
              - type: custom:button-card
                name: Spela upp ljud på iPhone X
                icon: mdi:volume-high
                template: icon_name
                tap_action:
                  action: call-service
                  service: notify.mobile_app_iphone
                  service_data:
                    title: Hitta min iPhone
                    message: Här är jag
                    data:
                      push:
                        sound:
                          name: findmy.wav
                          critical: 1
                          volume: 1

        - type: map
          default_zoom: 16
          dark_mode: true
          entities:
            - device_tracker.iphone
          card_mod:
            style:
              .: |
                #root {
                  height: 25em;
                  padding-bottom: 0 !important;
                }
                ha-icon-button {
                  color: var(--primary-color);
                  zoom: 140%;
                  margin-left: -0.2em;
                }
                ha-card {
                  border-top: 2px solid #1a1a1a;
                  border-radius: 0;
                  transition: none;
                  margin-bottom: -4px !important;
                  height: 25em !important;
                }
              ha-map$: |
                #map {
                  background-color: #191919 !important;
                }
                .leaflet-control-attribution {
                  display: none;
                }
                .leaflet-bar a {
                  background-color: rgba(115, 123, 124, 0.2) !important;
                  color: #9da0a2 !important;
                  backdrop-filter: blur(0.25em);
                  zoom: 140%;
                }
                a.leaflet-control-zoom-in {
                  border-bottom: 1px solid #181818 !important;
                }
                .leaflet-pane.leaflet-tile-pane {
                  filter: invert(0.95) grayscale(0.95) contrast(95%);
                }
